# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 17:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(max_length=6)),
                ('street_name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('state_provence', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=20)),
                ('address_type', models.CharField(choices=[('B', 'billing'), ('M', 'mailing')], default='B', max_length=2, verbose_name='address type')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30, verbose_name='state or provence')),
                ('country', models.CharField(max_length=2, verbose_name='country abbreviation')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('miles', models.PositiveSmallIntegerField(default=1000)),
                ('international', models.BooleanField(default=False)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Airline')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='api.City')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='api.City')),
            ],
            options={
                'verbose_name_plural': 'Flights',
            },
        ),
        migrations.CreateModel(
            name='FlightInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveSmallIntegerField(default=80)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('FF', 'Future Flight'), ('IF', 'In Flight'), ('AR', 'Arrived'), ('DL', 'Delayed')], default='FF', max_length=2, verbose_name='status')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='api.Flight')),
            ],
            options={
                'verbose_name': 'Flight Instance',
                'verbose_name_plural': 'Flight Instances',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number_of_rooms', models.PositiveSmallIntegerField(default=20)),
                ('cities', models.ManyToManyField(to='api.City')),
            ],
            options={
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupied', to='api.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('VS', 'Visa'), ('AE', 'American Express'), ('MC', 'MasterCard')], default='MC', max_length=2, verbose_name='card type')),
                ('number', models.CharField(max_length=16)),
                ('cvc', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=60)),
                ('expiration', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.PositiveSmallIntegerField(default=1)),
                ('guests', models.PositiveSmallIntegerField(default=1)),
                ('check_in_date', models.DateField()),
                ('duration', models.PositiveSmallIntegerField(default=1)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.Profile')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total', models.DecimalField(decimal_places=2, max_digits=4)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.Payment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.Profile')),
            ],
            options={
                'ordering': ['datetime'],
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.Transaction'),
        ),
        migrations.AddField(
            model_name='payment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='booking',
            name='flightinstances',
            field=models.ManyToManyField(blank=True, null=True, to='api.FlightInstance'),
        ),
        migrations.AddField(
            model_name='booking',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.Transaction'),
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together=set([('number', 'airline')]),
        ),
    ]
