# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-28 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_city', models.CharField(max_length=255)),
                ('depart_state', models.CharField(max_length=2)),
                ('depart_datetime', models.DateTimeField(default='')),
                ('arrive_city', models.CharField(max_length=255)),
                ('arrive_state', models.CharField(max_length=2)),
                ('arrive_datetime', models.DateTimeField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.IntegerField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
