# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-05 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('cust_name', models.CharField(max_length=255)),
                ('airline_name', models.CharField(max_length=255)),
                ('credit_type', models.CharField(max_length=255)),
                ('credit_name', models.CharField(max_length=255)),
                ('credit_number', models.IntegerField()),
                ('credit_expiration', models.DateTimeField(default='')),
                ('credit_security', models.IntegerField()),
                ('depart_city', models.CharField(max_length=255)),
                ('depart_state', models.CharField(max_length=2)),
                ('depart_datetime', models.DateTimeField(default='')),
                ('arrive_city', models.CharField(max_length=255)),
                ('arrive_state', models.CharField(max_length=2)),
                ('arrive_datetime', models.DateTimeField(default='')),
                ('num_passengers', models.IntegerField()),
                ('mileage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('arrive_city', models.CharField(max_length=255)),
                ('arrive_state', models.CharField(max_length=2)),
                ('arrive_datetime', models.DateTimeField(default='')),
                ('depart_city', models.CharField(max_length=255)),
                ('depart_state', models.CharField(max_length=2)),
                ('depart_datetime', models.DateTimeField(default='')),
                ('airline_name', models.CharField(max_length=255)),
                ('hotel_name', models.CharField(max_length=255)),
                ('hotel_street', models.CharField(max_length=255)),
                ('hotel_city', models.CharField(max_length=255)),
                ('hotel_state', models.CharField(max_length=2)),
                ('hotel_zip', models.IntegerField()),
                ('price_low', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_high', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('feedback_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.IntegerField()),
                ('depart_city', models.CharField(max_length=255)),
                ('depart_state', models.CharField(max_length=2)),
                ('depart_datetime', models.DateTimeField(default='')),
                ('arrive_city', models.CharField(max_length=255)),
                ('arrive_state', models.CharField(max_length=2)),
                ('arrive_datetime', models.DateTimeField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('intl', models.BooleanField()),
                ('status', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=255)),
                ('credit_type', models.CharField(max_length=255)),
                ('credit_name', models.CharField(max_length=255)),
                ('credit_number', models.IntegerField()),
                ('credit_expiration', models.DateTimeField(default='')),
                ('credit_security', models.IntegerField()),
                ('num_rooms', models.IntegerField()),
                ('num_occupant', models.IntegerField()),
                ('hotel_name', models.CharField(max_length=255)),
                ('hotel_street', models.CharField(max_length=255)),
                ('hotel_city', models.CharField(max_length=255)),
                ('hotel_state', models.CharField(max_length=2)),
                ('hotel_zip', models.IntegerField()),
                ('hotel_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('arrive_datetime', models.DateTimeField(default='')),
                ('depart_datetime', models.DateTimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('name_first', models.CharField(max_length=255)),
                ('name_middle', models.CharField(max_length=255)),
                ('name_last', models.CharField(max_length=255)),
                ('address_street', models.CharField(max_length=255)),
                ('address_city', models.CharField(max_length=255)),
                ('address_state', models.CharField(max_length=255)),
                ('address_zip', models.CharField(max_length=255)),
                ('credit_type', models.CharField(max_length=255)),
                ('credit_name', models.CharField(max_length=255)),
                ('credit_number', models.IntegerField()),
                ('credit_expiration', models.DateTimeField(default='')),
                ('credit_security', models.IntegerField()),
                ('user_miles', models.IntegerField()),
            ],
        ),
    ]
