# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-03 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180728_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=255)),
                ('airline_name', models.CharField(max_length=255)),
                ('credit_type', models.CharField(max_length=255)),
                ('credit_name', models.CharField(max_length=255)),
                ('credit_number', models.IntegerField()),
                ('credit_expiration', models.DateTimeField(default='')),
                ('credit_security', models.IntegerField()),
                ('depart_city', models.CharField(max_length=255)),
                ('depart_state', models.CharField(max_length=2)),
                ('depart_datetime', models.DateTimeField(default='')),
                ('arrive_city', models.CharField(max_length=255)),
                ('arrive_state', models.CharField(max_length=2)),
                ('arrive_datetime', models.DateTimeField(default='')),
                ('num_passengers', models.IntegerField()),
                ('mileage', models.IntegerField()),
            ],
        ),
    ]
