# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-04 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_deal'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=255)),
                ('credit_type', models.CharField(max_length=255)),
                ('credit_name', models.CharField(max_length=255)),
                ('credit_number', models.IntegerField()),
                ('credit_expiration', models.DateTimeField(default='')),
                ('credit_security', models.IntegerField()),
            ],
        ),
    ]
