# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-04 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='credit_expiration',
            new_name='credit_exp',
        ),
    ]
