# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-04 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20180804_0921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TravelUser',
        ),
        migrations.RenameField(
            model_name='traveluser',
            old_name='cred_exp',
            new_name='credit_expiration',
        ),
        migrations.RenameField(
            model_name='traveluser',
            old_name='cred_name',
            new_name='credit_name',
        ),
        migrations.RenameField(
            model_name='traveluser',
            old_name='cred_number',
            new_name='credit_number',
        ),
        migrations.RenameField(
            model_name='traveluser',
            old_name='cred_security',
            new_name='credit_security',
        ),
        migrations.RenameField(
            model_name='traveluser',
            old_name='cred_type',
            new_name='credit_type',
        ),
    ]
