# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-04 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20180804_0923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TravelUser',
            new_name='User',
        ),
    ]
